### ISSUE TITLE
[1.12.2-1.5.0.2] Crashes on a dedicated server - world.getLoadedEntityList() is client only

### ISSUE THREAD

**Issue by TigerWalts** [ArekkuusuJerii/BetterHurtTimer#33]
`1.12.2-1.5.0.2` is not server compatible. An event handler uses a client-only method `world.getLoadedEntityList()`.

```
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.World.func_72910_y()Ljava/util/List;
    at arekkuusu.betterhurttimer.common.Events.onNonLivingEntityUpdate(Events.java:45)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_516_Events_onNonLivingEntityUpdate_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

https://github.com/BunnyCinnamon/BetterHurtTimer/blob/16aa5c9cfb0ac84127145da88a7df1fc731d4777/src/main/java/arekkuusu/betterhurttimer/common/Events.java#L45

**Comment by naqaden** [comment]
Seems to be fixed. My dedicated server with 1.12.2-1.5.0.6 does not crash.
